//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Controls1.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls1 : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls1()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls1"",
    ""maps"": [
        {
            ""name"": ""Camera1ActionMap"",
            ""id"": ""1d6b73f9-cb14-4af3-8448-a61ee8268cca"",
            ""actions"": [
                {
                    ""name"": ""Moving"",
                    ""type"": ""Value"",
                    ""id"": ""12250556-c007-4404-af5a-d3bb19fdabe2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""7f563622-8273-4799-a54f-f0c2cd1cea8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""b8e0c4a5-a751-45a9-8480-ae91c7a53310"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Moving2"",
                    ""type"": ""Value"",
                    ""id"": ""7461f875-322c-4b8b-9696-937250b21b71"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7ab70f92-3917-4f02-b552-3c88cbed63a8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""67b72761-15f1-493b-b0be-4ae508b28887"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3d7991a0-f909-487a-a493-53bde25a3b3f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""13a8b7c4-40ac-4f75-9159-a5d212c86996"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""eb6d7b0c-108e-49f0-954a-1f01acca5bf4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""457c2131-802f-41f4-a17e-b892cbc02047"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84ae503a-8da0-454a-a420-8966ff8a8b0e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4ef76203-9518-406c-b88e-1d3f53c87c7c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8c7e3e7b-9b72-491f-ba14-0060b27fa3d2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""94a2a542-7989-4c0b-9435-45cfc7f4a512"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b89157cf-3e90-4184-ae4a-3463f651beff"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8c9c9b2b-df19-4c24-ad64-a1ca477e22d0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Camera1ActionMap
        m_Camera1ActionMap = asset.FindActionMap("Camera1ActionMap", throwIfNotFound: true);
        m_Camera1ActionMap_Moving = m_Camera1ActionMap.FindAction("Moving", throwIfNotFound: true);
        m_Camera1ActionMap_Throw = m_Camera1ActionMap.FindAction("Throw", throwIfNotFound: true);
        m_Camera1ActionMap_Pause = m_Camera1ActionMap.FindAction("Pause", throwIfNotFound: true);
        m_Camera1ActionMap_Moving2 = m_Camera1ActionMap.FindAction("Moving2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camera1ActionMap
    private readonly InputActionMap m_Camera1ActionMap;
    private ICamera1ActionMapActions m_Camera1ActionMapActionsCallbackInterface;
    private readonly InputAction m_Camera1ActionMap_Moving;
    private readonly InputAction m_Camera1ActionMap_Throw;
    private readonly InputAction m_Camera1ActionMap_Pause;
    private readonly InputAction m_Camera1ActionMap_Moving2;
    public struct Camera1ActionMapActions
    {
        private @Controls1 m_Wrapper;
        public Camera1ActionMapActions(@Controls1 wrapper) { m_Wrapper = wrapper; }
        public InputAction @Moving => m_Wrapper.m_Camera1ActionMap_Moving;
        public InputAction @Throw => m_Wrapper.m_Camera1ActionMap_Throw;
        public InputAction @Pause => m_Wrapper.m_Camera1ActionMap_Pause;
        public InputAction @Moving2 => m_Wrapper.m_Camera1ActionMap_Moving2;
        public InputActionMap Get() { return m_Wrapper.m_Camera1ActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Camera1ActionMapActions set) { return set.Get(); }
        public void SetCallbacks(ICamera1ActionMapActions instance)
        {
            if (m_Wrapper.m_Camera1ActionMapActionsCallbackInterface != null)
            {
                @Moving.started -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnMoving;
                @Moving.performed -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnMoving;
                @Moving.canceled -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnMoving;
                @Throw.started -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnThrow;
                @Throw.performed -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnThrow;
                @Throw.canceled -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnThrow;
                @Pause.started -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnPause;
                @Moving2.started -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnMoving2;
                @Moving2.performed -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnMoving2;
                @Moving2.canceled -= m_Wrapper.m_Camera1ActionMapActionsCallbackInterface.OnMoving2;
            }
            m_Wrapper.m_Camera1ActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Moving.started += instance.OnMoving;
                @Moving.performed += instance.OnMoving;
                @Moving.canceled += instance.OnMoving;
                @Throw.started += instance.OnThrow;
                @Throw.performed += instance.OnThrow;
                @Throw.canceled += instance.OnThrow;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Moving2.started += instance.OnMoving2;
                @Moving2.performed += instance.OnMoving2;
                @Moving2.canceled += instance.OnMoving2;
            }
        }
    }
    public Camera1ActionMapActions @Camera1ActionMap => new Camera1ActionMapActions(this);
    public interface ICamera1ActionMapActions
    {
        void OnMoving(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnMoving2(InputAction.CallbackContext context);
    }
}
